name: train_seat_exchange
description: Train seat exchange mobile app for Indian Railways passengers
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_auth: ^5.1.2
  firebase_core: ^3.3.0
  
  # State Management
  provider: ^6.1.1
  
  # Network
  http: ^1.1.2
  dio: ^5.4.0
  
  # Phone Dialer
  url_launcher: ^6.2.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
